version: '3.8'

services:
  nginx:
    build:
      context: .docker/builds/nginx
      args:
        PUID: $DOCKER_PUID
        PGID: $DOCKER_PGID
    volumes:
      - ./:/var/www/app
      - .docker/data/logs/nginx:/var/log/nginx
    ports:
      - ${DOCKER_NGINX_PORT1-80}:80
      - ${DOCKER_NGINX_PORT2:-8080}:8080
    networks:
      app_network:
        { }

  php:
    build:
      context: .docker/builds/php
      args:
        PUID: ${DOCKER_PUID}
        PGID: ${DOCKER_PGID}
    volumes:
      - ./:/var/www/app
    working_dir: /var/www/app
    ports:
      - ${PHP_HOST_PORT2:-9000}:9000
    environment:
      DB_DATABASE: $MYSQL_DATABASE
      DB_USERNAME: $MYSQL_USERNAME
      DB_PASSWORD: $MYSQL_PASSWORD
      PHP_IDE_CONFIG: "serverName=Docker"
      XDEBUG_MODE: ${XDEBUG_MODE}
    networks:
      app_network:
        { }

  mysql:
    image: mysql:8.4
    command: "--mysql-native-password=ON"
    volumes:
      - .docker/data/mysql:/var/lib/mysql
      - .docker/builds/mysql:/etc/mysql/conf.d
    ports:
      - ${MYSQL_HOST_PORT-3306}:3306
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USERNAME: $MYSQL_USERNAME
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    networks:
      app_network:
        { }

  redis:
    image: redis:latest
    ports:
      - ${REDIS_HOST_PORT-6379}:6379
    networks:
      app_network:
        { }

networks:
  app_network: